### ISSUE TITLE
Any plans for stacked bars?

### ISSUE THREAD

**Issue by srswanson** [cnharris10/CHRadarGraph#1]
I'm wondering if you have any plans to add stacked bars so this library could be used to create a wind rose?

**Comment by cnharris10** [comment]
Send me an example, not quite sure what you mean.

All options are on the table.

**Comment by srswanson** [comment]
Here is the Wikipedia article on a Wind Rose.  [https://en.wikipedia.org/wiki/Wind_rose](url)

**Comment by cnharris10** [comment]
It can be done as a wind rose today. I would only need to add the ability to have label son the outermost ring

**Comment by srswanson** [comment]
Cool - Thank you.  I'll build a sample app to try it out.

**Comment by cnharris10** [comment]
Let me know what else you would need for it
